"""purchase_tabel

Revision ID: 1b3cd6d6d6ea
Revises: 46d8e1fd13d2
Create Date: 2022-10-24 17:05:43.080134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b3cd6d6d6ea'
down_revision = '46d8e1fd13d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p_invoice_no', sa.String(length=100), nullable=True),
    sa.Column('purchase_type', sa.Integer(), nullable=True),
    sa.Column('lc_date', sa.DATE(), nullable=True),
    sa.Column('lc_no', sa.String(length=100), nullable=True),
    sa.Column('challan_date', sa.DATE(), nullable=True),
    sa.Column('total_vds', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('grand_total', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('total_tax', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('vendor_invoice', sa.String(length=255), nullable=True),
    sa.Column('custom_house', sa.String(length=255), nullable=True),
    sa.Column('country_origin', sa.String(length=255), nullable=True),
    sa.Column('boe_item_no', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=155), nullable=True),
    sa.Column('cpc_code_id', sa.String(length=255), nullable=True),
    sa.Column('entry_date', mysql.DATETIME(), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('hs_code_id', sa.Integer(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('qty', mysql.FLOAT(), nullable=True),
    sa.Column('rate', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('rate_value', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('vatable_value', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('vat_percent', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('vat_amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('cd_percent', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('cd_amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('sd_percent', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('sd_amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('rd_percent', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('rd_amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('at_amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('ait_amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('tti_percent', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('tti_amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('vat_type', sa.String(length=100), nullable=True),
    sa.Column('vds', sa.String(length=100), nullable=True),
    sa.Column('rebate', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.DATE(), nullable=True),
    sa.Column('entry_date', mysql.DATETIME(), nullable=True),
    sa.Column('sub_total', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('grand_total', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_line')
    op.drop_table('purchase')
    # ### end Alembic commands ###
