"""Customers Table

Revision ID: 26e8299c418f
Revises: 2a100b47edb8
Create Date: 2022-10-03 11:58:08.916725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e8299c418f'
down_revision = '2a100b47edb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('email_address', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('customer_type', sa.String(length=100), nullable=True),
    sa.Column('customer_address', sa.String(length=100), nullable=True),
    sa.Column('shipping_address', sa.String(length=100), nullable=True),
    sa.Column('shipping_country', sa.String(length=100), nullable=True),
    sa.Column('customer_bin', sa.String(length=100), nullable=True),
    sa.Column('customer_tin', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
