"""Units Table

Revision ID: 2a100b47edb8
Revises: 
Create Date: 2022-09-27 13:06:34.372655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a100b47edb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=100), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('countries', 'shortname',
               existing_type=mysql.VARCHAR(length=3),
               nullable=True)
    op.alter_column('countries', 'country_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('countries', 'country_code',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'country_code',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('countries', 'country_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('countries', 'shortname',
               existing_type=mysql.VARCHAR(length=3),
               nullable=False)
    op.drop_table('units')
    # ### end Alembic commands ###
