"""treasury_chalan_table

Revision ID: 4f7dd2555c62
Revises: 90237fe8bc53
Create Date: 2022-11-07 18:44:39.400390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f7dd2555c62'
down_revision = '90237fe8bc53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treasury_chalan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_chalan_no', sa.String(length=100), nullable=True),
    sa.Column('t_bank', sa.String(length=100), nullable=True),
    sa.Column('t_branch', sa.String(length=100), nullable=True),
    sa.Column('t_account_code', sa.String(length=100), nullable=True),
    sa.Column('t_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('t_date', sa.DATE(), nullable=True),
    sa.Column('execute_date', sa.DATE(), nullable=True),
    sa.Column('t_type', sa.Integer(), nullable=True),
    sa.Column('business_type', sa.Integer(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treasury_chalan')
    # ### end Alembic commands ###
