"""Supplier Table

Revision ID: 611d81deda3b
Revises: 26e8299c418f
Create Date: 2022-10-11 17:28:11.028248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611d81deda3b'
down_revision = '26e8299c418f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=100), nullable=True),
    sa.Column('email_address', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=100), nullable=True),
    sa.Column('country_id', sa.String(length=100), nullable=True),
    sa.Column('supplier_type', sa.String(length=100), nullable=True),
    sa.Column('supplier_address', sa.String(length=100), nullable=True),
    sa.Column('supplier_bin', sa.String(length=100), nullable=True),
    sa.Column('supplier_tin', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppliers')
    # ### end Alembic commands ###
