"""credit_note_table

Revision ID: 817f6bef9a5c
Revises: e3bc2fb196da
Create Date: 2022-11-14 12:49:38.601478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '817f6bef9a5c'
down_revision = 'e3bc2fb196da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_note_no', sa.String(length=100), nullable=True),
    sa.Column('credit_note_type', sa.Integer(), nullable=True),
    sa.Column('cn_issue_date', sa.DATE(), nullable=True),
    sa.Column('sales_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_info', sa.String(length=100), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_vat', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_sd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_note_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_note_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('rate', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('s_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('s_vat_percent', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('s_vat_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('s_sd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('return_qty', sa.Integer(), nullable=True),
    sa.Column('return_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('return_vat', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('return_sd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('entry_date', sa.DATE(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_note_line')
    op.drop_table('credit_note')
    # ### end Alembic commands ###
