"""issue_vds_tabel

Revision ID: 864918a58de7
Revises: bf611c020b10
Create Date: 2022-10-31 14:28:53.966231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '864918a58de7'
down_revision = 'bf611c020b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_vds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vds_no', sa.String(length=100), nullable=True),
    sa.Column('vds_type', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.DATE(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_vat', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_vds', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_payment', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_vds_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vds_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('invoice_no', sa.String(length=100), nullable=True),
    sa.Column('inv_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('inv_date', sa.DATE(), nullable=True),
    sa.Column('vat_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('vds_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('branch_name', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('deposit_serial', sa.String(length=50), nullable=True),
    sa.Column('deposit_date', sa.DATE(), nullable=True),
    sa.Column('entry_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_vds_line')
    op.drop_table('issue_vds')
    # ### end Alembic commands ###
