"""receive_vds_table

Revision ID: 90237fe8bc53
Revises: 864918a58de7
Create Date: 2022-11-01 17:49:56.146162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90237fe8bc53'
down_revision = '864918a58de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receive_vds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vds_no', sa.String(length=100), nullable=True),
    sa.Column('vds_type', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.DATE(), nullable=True),
    sa.Column('vds_certificate_no', sa.String(length=100), nullable=True),
    sa.Column('receive_date', sa.DATE(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_vat', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_vds', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_receive', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receive_vds_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vds_id', sa.Integer(), nullable=True),
    sa.Column('invoice_no', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('inv_amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('inv_date', sa.DATE(), nullable=True),
    sa.Column('vat_amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('vds_amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('receive_amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('branch_name', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('deposit_serial', sa.String(length=50), nullable=True),
    sa.Column('deposit_date', sa.DATE(), nullable=True),
    sa.Column('entry_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receive_vds_line')
    op.drop_table('receive_vds')
    # ### end Alembic commands ###
