"""sales_table

Revision ID: bf611c020b10
Revises: e4d5510b1c0c
Create Date: 2022-10-30 15:06:37.467558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf611c020b10'
down_revision = 'e4d5510b1c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('sale_center_id', sa.Integer(), nullable=True),
    sa.Column('sales_transfer_id', sa.Integer(), nullable=True),
    sa.Column('sale_date', sa.DATE(), nullable=True),
    sa.Column('sales_invoice', sa.String(length=100), nullable=True),
    sa.Column('vehicle_info', sa.String(length=100), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=True),
    sa.Column('sales_challan', sa.String(length=100), nullable=True),
    sa.Column('entry_date', mysql.DATETIME(), nullable=True),
    sa.Column('sales_type', sa.Integer(), nullable=True),
    sa.Column('trans_type', sa.Integer(), nullable=True),
    sa.Column('total_discount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_sd', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_vat', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('grand_total', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('hs_code_id', sa.Integer(), nullable=True),
    sa.Column('sales_id', sa.Integer(), nullable=True),
    sa.Column('qty', mysql.FLOAT(), nullable=True),
    sa.Column('rate', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('rate_value', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('discount_percent', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('discount_amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('value_after_discount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('sd_percent', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('sd_amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('vatable_value', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('vat_type', sa.String(length=100), nullable=True),
    sa.Column('vat_percent', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('vat_amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('vds', sa.String(length=100), nullable=True),
    sa.Column('sales_date', sa.DATE(), nullable=True),
    sa.Column('sub_total', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_line')
    op.drop_table('sales')
    # ### end Alembic commands ###
