"""company

Revision ID: e071abe05558
Revises: 0dee185b46eb
Create Date: 2022-09-25 18:04:07.812716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e071abe05558'
down_revision = '0dee185b46eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('email_address', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('invoice_logo', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('ac_number', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('business_nature', sa.String(length=100), nullable=True),
    sa.Column('business_economics', sa.String(length=100), nullable=True),
    sa.Column('vat_type', sa.String(length=100), nullable=True),
    sa.Column('bin_number', sa.String(length=100), nullable=True),
    sa.Column('tin_number', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=100), nullable=True),
    sa.Column('person_name', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('person_phone_number', sa.String(length=100), nullable=True),
    sa.Column('nid', sa.String(length=100), nullable=True),
    sa.Column('person_email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###
